on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Svelte App
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bun Setup
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: 'mise.toml'
      - name: Install
        run: bun install
      # - name: Lint
      #   run: bun lint
      - name: Svelte Check
        run: bun check
      - name: Build
        run: bun run build
      - name: Publish Artifact
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
